# Generated by Django 5.2.9 on 2025-12-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jenkins_integration', '0003_add_is_ip_manual_to_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20, unique=True, verbose_name='时间戳')),
                ('report_title', models.CharField(default='自动化测试报告', max_length=255, verbose_name='报告标题')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总测试用例数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('skipped_cases', models.IntegerField(default=0, verbose_name='跳过用例数')),
                ('broken_cases', models.IntegerField(default=0, verbose_name='中断用例数')),
                ('unknown_cases', models.IntegerField(default=0, verbose_name='未知状态用例数')),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='通过率')),
                ('min_duration', models.BigIntegerField(default=0, verbose_name='最小执行时间(ms)')),
                ('max_duration', models.BigIntegerField(default=0, verbose_name='最大执行时间(ms)')),
                ('sum_duration', models.BigIntegerField(default=0, verbose_name='总执行时间(ms)')),
                ('execution_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='执行时长')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], default='success', max_length=10, verbose_name='执行状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='jenkins_integration.jenkinsjob', verbose_name='关联Jenkins任务')),
            ],
            options={
                'verbose_name': '测试执行总览',
                'verbose_name_plural': '测试执行总览',
                'db_table': 'test_execution',
            },
        ),
        migrations.CreateModel(
            name='FeatureScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=100, verbose_name='场景名称')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('passed', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed', models.IntegerField(default=0, verbose_name='失败数')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='通过率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='test_report.testexecution', verbose_name='关联的执行')),
            ],
            options={
                'verbose_name': '特性场景',
                'verbose_name_plural': '特性场景',
                'db_table': 'feature_scenarios',
                'unique_together': {('execution', 'scenario_name')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('trivial', 'Trivial')], default='major', max_length=10, verbose_name='严重程度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='test_report.testexecution', verbose_name='关联的执行')),
            ],
            options={
                'verbose_name': '缺陷类别',
                'verbose_name_plural': '缺陷类别',
                'db_table': 'categories',
                'unique_together': {('execution', 'category_name')},
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=255, verbose_name='测试套名称')),
                ('total_cases', models.IntegerField(default=0)),
                ('passed_cases', models.IntegerField(default=0)),
                ('failed_cases', models.IntegerField(default=0)),
                ('skipped_cases', models.IntegerField(default=0)),
                ('broken_cases', models.IntegerField(default=0)),
                ('unknown_cases', models.IntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_duration', models.BigIntegerField(default=0)),
                ('max_duration', models.BigIntegerField(default=0)),
                ('sum_duration', models.BigIntegerField(default=0)),
                ('duration_seconds', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='执行时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='test_report.testexecution', verbose_name='关联的执行')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'db_table': 'test_suites',
                'unique_together': {('execution', 'suite_name')},
            },
        ),
    ]
