# Generated by Django 5.2.9 on 2025-12-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0004_remove_jenkinsjob_idx_jenkins_job_env_and_more'),
        ('test_report', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['job', 'created_at'], name='idx_job_created'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['timestamp'], name='idx_timestamp'),
        ),
    ]
