# Generated by Django 5.2.9 on 2025-12-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_report', '0002_testexecution_idx_job_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('parent_suite', models.CharField(max_length=255, verbose_name='父套件')),
                ('suite', models.CharField(blank=True, max_length=255, null=True, verbose_name='套件')),
                ('sub_suite', models.CharField(blank=True, max_length=255, null=True, verbose_name='子套件')),
                ('test_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试类')),
                ('test_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试方法')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('broken', 'Broken'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='状态')),
                ('start_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='开始时间')),
                ('stop_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='结束时间')),
                ('duration_in_ms', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_details', to='test_report.testexecution', verbose_name='关联的执行')),
            ],
            options={
                'verbose_name': '测试套件详情',
                'verbose_name_plural': '测试套件详情',
                'db_table': 'test_suite_details',
                'indexes': [models.Index(fields=['execution'], name='idx_execution_id'), models.Index(fields=['parent_suite'], name='idx_parent_suite')],
            },
        ),
    ]
