# Generated by Django 5.2.9 on 2025-12-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('username', models.CharField(default='', max_length=20, verbose_name='项目创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='上传文件')),
                ('info', models.JSONField(default=list, verbose_name='文件类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '文件列表',
                'verbose_name_plural': '文件列表',
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_variable', models.JSONField(blank=True, default=dict, null=True, verbose_name='全局变量')),
                ('debug_global_variable', models.JSONField(blank=True, default=dict, null=True, verbose_name='调试全局变量')),
                ('db', models.JSONField(blank=True, default=list, null=True, verbose_name='数据库配置')),
                ('headers', models.JSONField(blank=True, default=dict, null=True, verbose_name='全局请求头')),
                ('global_func', models.TextField(blank=True, default='# 全局工具函数，可以在测试用例的前置、断言脚本中直接调用\nimport base64\nimport hashlib\nimport time\n# 生成各种伪数据的库\nfrom faker import Faker\n\n# 实例化，中文\nfk = Faker(locale=\'zh_CN\')\n\n\ndef mobile():\n    """随机生成手机号"""\n    return fk.phone_number()\n\n\ndef name():\n    """随机生成中文名字"""\n    return fk.name()\n\n\ndef address():\n    """随机生成一个地址"""\n    return fk.address()\n\n\ndef city():\n    """随机生成一个城市名"""\n    return fk.city()\n\n\ndef company():\n    """随机生成一个公司名"""\n    return fk.company()\n\n\ndef postcode():\n    """随机生成一个邮编"""\n    return fk.postcode()\n\n\ndef email():\n    """随机生成一个邮箱号"""\n    return fk.email()\n\n\ndef date():\n    """随机生成一个日期1987-08-31"""\n    return fk.date()\n\n\ndef date_time():\n    """随机生成一个时间1988-12-11 01:35:30"""\n    return fk.date_time()\n\n\ndef ipv4():\n    """随机生成一个ipv4的地址18.63.34.130"""\n    return fk.ipv4()\n\n\ndef timestamp():\n    """生成当前时间戳1714358666.4879088"""\n    return time.time()\n\n\ndef md5_encode(args):\n    """md5加密，以指定的编码格式编码字符串"""\n    # 先把变量转成utf-8的编码格式\n    args = str(args).encode(\'utf-8\')\n    # md5加密\n    args_value = hashlib.md5(args).hexdigest()\n    # 返回\n    return args_value\n\n\ndef base64_encode(args):\n    """base64编码"""\n    # 先把变量转成utf-8的编码格式\n    args = str(args).encode(\'utf-8\')\n    # base64加密\n    base64_value = base64.b64encode(args).decode(encoding=\'utf-8\')\n    # 返回\n    return base64_value\n\n\ndef base64_decode(args):\n    """base64解密"""\n    # 原文转为二进制\n    args = str(args).encode("utf-8")\n    # base64解密(二进制)\n    decode_value = base64.b64decode(args)\n    # 转成字符串\n    encode_str = decode_value.decode("utf-8")\n    return encode_str\n\n\ndef sha1_encode(params):\n    """参数sha1加密"""\n    enc_data = hashlib.sha1()\n    enc_data.update(params.encode(encoding="utf-8"))\n    return enc_data.hexdigest()\n\n\ndef sha256_encode(params):\n    """参数sha256加密"""\n    enc_data = hashlib.sha256()\n    enc_data.update(params.encode(encoding="utf-8"))\n    return enc_data.hexdigest()\n\n\ndef sha512_encode(params):\n    """参数sha512加密"""\n    enc_data = hashlib.sha512()\n    enc_data.update(params.encode(encoding="utf-8"))\n    return enc_data.hexdigest()\n', null=True, verbose_name='全局工具函数')),
                ('name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('host', models.CharField(max_length=50, verbose_name='host地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('username', models.CharField(max_length=20, verbose_name='环境创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
                'db_table': 'environment',
            },
        ),
    ]
