# Generated by Django 5.2.9 on 2025-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='source',
            field=models.CharField(choices=[('manual', '手动创建'), ('jenkins', 'Jenkins同步')], default='manual', max_length=10, verbose_name='环境来源'),
        ),
    ]
