# Generated by Django 5.2.9 on 2025-12-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='接口名称')),
                ('username', models.CharField(max_length=20, verbose_name='接口创建人')),
                ('url', models.CharField(max_length=255, verbose_name='接口地址')),
                ('method', models.CharField(max_length=50, verbose_name='请求方法')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口列表',
                'verbose_name_plural': '接口列表',
                'db_table': 'interface',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='用例名称')),
                ('headers', models.JSONField(blank=True, default=dict, null=True, verbose_name='请求头配置')),
                ('request', models.JSONField(blank=True, default=dict, null=True, verbose_name='请求参数配置')),
                ('file', models.JSONField(blank=True, default=list, null=True, verbose_name='请求上传的文件参数')),
                ('setup_script', models.TextField(blank=True, default='# 前置脚本(python)\n# global_func：全局工具函数\n# data：用例数据\n# env：临时环境\n# ENV：全局环境\n# db：数据库操作对象\n', null=True, verbose_name='前置脚本')),
                ('teardown_script', models.TextField(blank=True, default='# 断言脚本(python)\n# global_func：全局工具函数\n# data：用例数据\n# response：响应对象response\n# env：临时环境\n# ENV：全局环境\n# db：数据库操作对象\n', null=True, verbose_name='断言脚本')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('username', models.CharField(max_length=20, verbose_name='用例创建人')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.interface', verbose_name='接口地址')),
            ],
            options={
                'verbose_name': '用例列表',
                'verbose_name_plural': '用例列表',
                'db_table': 'case',
            },
        ),
    ]
