# Generated by Django 5.2.9 on 2025-12-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interface', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('describe', models.CharField(blank=True, max_length=255, verbose_name='bug描述')),
                ('info', models.JSONField(blank=True, default=dict, verbose_name='bug的用例详情')),
                ('status', models.CharField(choices=[('1', '未处理bug'), ('2', '处理中bug'), ('3', '处理完bug'), ('4', '无效的bug')], default='1', max_length=10, verbose_name='bug状态')),
                ('level', models.CharField(choices=[('1', '严重'), ('2', '一般'), ('3', '轻微')], default='1', max_length=10, verbose_name='bug等级')),
                ('username', models.CharField(blank=True, default='', max_length=20, verbose_name='提交人')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.interface', verbose_name='所属接口')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_set', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Bug列表',
                'verbose_name_plural': 'Bug列表',
                'db_table': 'bug',
            },
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('handle', models.CharField(blank=True, max_length=20, verbose_name='操作内容')),
                ('update_user', models.CharField(blank=True, max_length=20, verbose_name='操作人')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug.bug', verbose_name='bug的接口')),
            ],
            options={
                'verbose_name': 'Bug记录',
                'verbose_name_plural': 'Bug记录',
                'db_table': 'handle',
            },
        ),
    ]
