"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-nulqz=&y*06mbb%&&#@4_kh(+x^bmlb^gnmc65*owng(^1zacq"

# SECURITY WARNING: don't run with debug turned on in production!
# 模式配置
DEBUG = True

# 访问域名设置
ALLOWED_HOSTS = ['*']

# 注册app应用
# Application definition
INSTALLED_APPS = [
    # 后端页面优化插件
    'simpleui',
    # Django内置模块
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 过滤插件
    'django_filters',
    # 实现对前端跨域请求的支持
    'corsheaders',
    # 注册应用插件
    'rest_framework',
    # JWT认证
    'rest_framework_simplejwt',
    # 定时任务
    'django_celery_beat',
    # 接口文档插件
    'drf_spectacular',
    'drf_spectacular_sidecar',
    # 定时任务监控插件
    'django_celery_results',
    # 注册平台应用
    "user.apps.UserConfig",
    "project.apps.ProjectConfig",
    "interface.apps.InterfaceConfig",
    "scene.apps.SceneConfig",
    "plan.apps.PlanConfig",
    "cronjob.apps.CronjobConfig",
    "bug.apps.BugConfig"
]

# 注册中间件
MIDDLEWARE = [
    # 安全性
    "django.middleware.security.SecurityMiddleware",
    # 会话管理
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 加上corsheaders的中间件，实现对跨域请求的支持
    "corsheaders.middleware.CorsMiddleware",
    # 通用的中间件
    "django.middleware.common.CommonMiddleware",
    # CSRF保护
    # "django.middleware.csrf.CsrfViewMiddleware",
    # 认证
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # 消息
    "django.contrib.messages.middleware.MessageMiddleware",
    # X-Frame-Options头
    "django.middleware.clickjacking.XFrameOptionsMiddleware"
]

# 指定根路由位置，格式：ROOT_URLCONF = "项目工程同名目录.urls"
ROOT_URLCONF = "backend.urls"

# 模板
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # 内置上下文处理器
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI配置
WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 数据库配置
if DEBUG:
    DATABASES = {
        # 开发环境，默认使用mysql数据库
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'django',
            'USER': 'root',
            'PASSWORD': '123456py',
            'HOST': '192.168.27.132',
            'PORT': '3306',
        }
    }
else:
    DATABASES = {
        # 线上环境，默认使用mysql数据库
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'django',
            'USER': 'root',
            'PASSWORD': '123456py',
            'HOST': '192.168.27.132',
            'PORT': '3306',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# 密码验证配置
AUTH_PASSWORD_VALIDATORS = [
    # 内置验证器
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# 国际化和本地化配置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
# 是否支持国际化
USE_I18N = True
# 是否支持本地化
USE_L10N = True
# 关闭timezone时区
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# 静态文件配置
STATIC_URL = "static/"
# 后台网页图标，生产环境禁用
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# 默认主键字段类型
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 项目日志配置
LOGGING = {
    'version': 1,
    # 禁用已经存在的日志器
    'disable_existing_loggers': False,
    # 日志信息显示的格式
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    # 对日志进行过滤
    'filters': {
        # django在debug模式下才输出日志
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    # 日志处理方法
    'handlers': {
        # 向终端输出日志
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 向文件中输出日志
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            # 后端服务日志文件的位置
            'filename': BASE_DIR / 'logs/py.log',
            'maxBytes': 30 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
        # 向文件中输出日志
        'celery': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            # celery日志文件的位置
            'filename': BASE_DIR / 'logs/celery.log',
            'maxBytes': 30 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
    },
    # 日志器
    'loggers': {
        # 定义名为django的日志器
        'django': {
            # 可以同时向终端与文件中输出日志
            'handlers': ['console', 'file'],
            # 是否继续传递日志信息
            'propagate': True,
            # 日志器接收的最低日志级别
            'level': 'INFO',
        },
        # 定义了一个名为celery的日志器
        'celery': {
            'handlers': ['console', 'celery'],
            'propagate': True,
            'level': 'INFO',
        },
    }
}

# 指定本项目用户模型
AUTH_USER_MODEL = 'user.User'

# 使用自定义的认证类进行身份认证，登录时验证用户信息
AUTHENTICATION_BACKENDS = [
    'user.authenticate.MyBackend'
]

REST_FRAMEWORK = {
    # 配置jwt鉴权和session认证登录方式
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # JWT认证
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # session认证
        'rest_framework.authentication.SessionAuthentication',
        # Basic认证
        'rest_framework.authentication.BasicAuthentication',
    ),
    # 配置DRF使用过滤器（通过django_filters插件来进行过虑）
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    # 接口文档
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

# 接口文档
SPECTACULAR_SETTINGS = {
    'TITLE': 'API接口文档',
    'DESCRIPTION': '接口测试平台项目在线接口文档',
    'VERSION': 'V0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': None,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "/static/media/favicon.ico",
    "REDOC_DIST": "SIDECAR",
}

# 配置token
SIMPLE_JWT = {
    # 访问令牌的有效时间
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    # 刷新令牌的有效时间
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
    # 若为True，则刷新后新的refresh_token有更新的有效时间
    "ROTATE_REFRESH_TOKENS": False,
    # 若为True，刷新后的token将添加到黑名单中
    "BLACKLIST_AFTER_ROTATION": True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    # 使用唯一不变的数据库字段，将包含在生成的令牌中以标识用户
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id'
}

# celery的配置
# 关掉celery的默认日志
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
# 任务队列配置，生产环境使用redis，测试环境使用内存，服务器192.168.27.132，密码123456py
CELERY_BROKER_URL = 'redis://:123456py@192.168.27.132:6379/4'
# 使用django-orm作为结果存储
CELERY_RESULT_BACKEND = 'django-db'
# 使用django_celery_beat插件用来动态配置任务
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# 官方用来修复CELERY_ENABLE_UTC = False和USE_TZ = False时间比较错误的问题
DJANGO_CELERY_BEAT_TZ_AWARE = False
# 关闭celery的时区，指定时区
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE
# 防止死锁
CELERYD_FORCE_EXECV = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 允许所有用户跨域访问
CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS指明在跨域访问中，后端是否支持对cookie的操作
CORS_ALLOW_CREDENTIALS = True
# 请求方法
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

# 指定上传文件路径
MEDIA_ROOT = BASE_DIR / 'files'

# 隐藏右侧simple广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
# 设置默认主题，指向主题css文件名：使用Admin Lte风格
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
# 登录页粒子动画，默认开启
# SIMPLEUI_LOGIN_PARTICLES = False
# 离线模式，默认从本地读取所有资源
SIMPLEUI_STATIC_OFFLINE = True
# 去掉默认Logo或换成自己Logo链接
SIMPLEUI_LOGO = '/static/media/favicon.ico'

# 自定义菜单配置
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭
    'system_keep': False,
    # 用于菜单排序和过滤，不填此字段为默认排序和全部显示。空列表[]为全部不显示
    'menu_display': ['用户管理', '项目管理', '接口管理', '测试套件', '定时任务', '测试计划', 'Bug管理', '任务监控'],
    # 设置是否开启动态菜单，默认为False。如果开启，则会在每次用户登陆时刷新展示菜单内容
    'dynamic': True,
    'menus': [
        {
            'app': 'user',
            'name': '用户管理',
            'icon': 'fas fa-user-shield',
            'models': [{
                'name': '用户列表',
                'icon': 'fa fa-user',
                'url': 'user/user/'
            },
                {
                    'name': '角色管理',
                    'icon': 'fas fa-users-cog',
                    'url': 'user/role/'
                }
            ]
        },
        {
            'app': 'project',
            'name': '项目管理',
            'icon': 'fas fa-archive',
            'models': [{
                'name': '项目列表',
                'url': 'project/project/',
            },
                {
                    'name': '文件列表',
                    'url': 'project/file/',
                    'icon': 'fa fa-upload',
                },
                {
                    'name': '测试环境',
                    'url': 'project/environment/',
                    'icon': 'fa fa-database',
                },
            ]
        },
        {
            'app': 'interface',
            'name': '接口管理',
            'icon': 'fas fa-plug',
            'models': [{
                'name': '接口列表',
                'url': 'interface/interface/'
            },
                {
                    'name': '用例列表',
                    'url': 'interface/case/',
                },
            ]
        },
        {
            'app': 'scene',
            'name': '测试套件',
            'icon': 'fas fa-sitemap',
            'models': [{
                'name': '测试套件',
                'url': 'scene/scene/'
            },
                {
                    'name': '测试步骤',
                    'url': 'scene/step/',
                    'icon': 'fas fa-signal'
                },
            ]
        },
        {
            'app': 'cronjob',
            'name': '定时任务',
            'icon': 'fa fa-th-list',
            'models': [{
                'name': '任务列表',
                'url': 'cronjob/cronjob/',
                'icon': 'fa fa-hourglass'
            },
            ]
        },
        {
            'app': 'plan',
            'name': '测试计划',
            'icon': 'fa fa-calendar',
            'models': [{
                'name': '测试计划',
                'url': 'plan/plan/'
            },
                {
                    'name': '运行记录',
                    'url': 'plan/record/',
                    'icon': 'fas fa-edit'
                },
                {
                    'name': '测试报告',
                    'url': 'plan/report/',
                    'icon': 'fas fa-calculator'
                },
            ]
        },
        {
            'app': 'bug',
            'name': 'Bug管理',
            'icon': 'fa fa-bug',
            'models': [{
                'name': 'Bug列表',
                'url': 'bug/bug/'
            },
                {
                    'name': 'Bug记录',
                    'url': 'bug/handle/',
                    'icon': 'fa fa-book'
                },
            ]
        },
        {
            'app': 'monitor',
            'name': '任务监控',
            'icon': 'fa fa-binoculars',
            'models': [{
                'name': '小组监控',
                'url': 'django_celery_results/groupresult/',
                'icon': 'fa fa-users'
            },
                {
                    'name': '任务监控',
                    'url': 'django_celery_results/taskresult/',
                    'icon': 'fa fa-archive'
                },
            ]
        }
    ]
}

# 打包后端静态文件，生产环境启用
# STATIC_ROOT = BASE_DIR / 'static'
