# Generated by Django 5.2.9 on 2025-12-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('username', models.CharField(max_length=20, verbose_name='计划创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='project.project', verbose_name='所属项目')),
                ('scene', models.ManyToManyField(default=list, to='scene.scene', verbose_name='包含的测试套件')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='执行时间')),
                ('all', models.IntegerField(blank=True, default=0, verbose_name='总用例数')),
                ('success', models.IntegerField(blank=True, default=0, verbose_name='通过用例数')),
                ('fail', models.IntegerField(blank=True, default=0, verbose_name='失败用例数')),
                ('error', models.IntegerField(blank=True, default=0, verbose_name='错误用例数')),
                ('pass_rate', models.CharField(blank=True, default='0', max_length=20, verbose_name='通过率（%）')),
                ('tester', models.CharField(blank=True, max_length=20, verbose_name='执行者')),
                ('status', models.CharField(max_length=10, verbose_name='执行状态')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.environment', verbose_name='测试环境')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '运行记录',
                'verbose_name_plural': '运行记录',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(blank=True, default=dict, verbose_name='报告数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.record', verbose_name='运行记录id')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'report',
            },
        ),
    ]
