# Generated by Django 5.2.9 on 2025-12-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0006_remove_jenkinsjob_idx_jenkins_job_parent_and_more'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='jenkins_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plans', to='jenkins_integration.jenkinsjob', verbose_name='关联的Jenkins测试脚本'),
        ),
    ]
