# Generated by Django 5.2.9 on 2025-12-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_jenkins_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='jenkins_job',
        ),
        migrations.AddField(
            model_name='plan',
            name='script_bind_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='脚本绑定时间'),
        ),
        migrations.AddField(
            model_name='plan',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='test_scripts/%Y/%m/', verbose_name='测试脚本文件'),
        ),
        migrations.AddField(
            model_name='plan',
            name='script_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='脚本文件名'),
        ),
        migrations.AddField(
            model_name='plan',
            name='script_type',
            field=models.CharField(blank=True, choices=[('exported', '导出'), ('uploaded', '上传')], max_length=20, null=True, verbose_name='脚本来源'),
        ),
    ]
