# Generated by Django 5.2.9 on 2025-12-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, verbose_name='任务创建人')),
                ('name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('rule', models.CharField(default='*/1 * * * *', max_length=20, verbose_name='执行规则')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.environment', verbose_name='测试环境')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan', verbose_name='测试计划')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronjob', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
                'db_table': 'cronjob',
            },
        ),
    ]
