# Generated by Django 5.2.9 on 2025-12-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
        ('jenkins_integration', '0006_remove_jenkinsjob_idx_jenkins_job_parent_and_more'),
        ('plan', '0003_remove_plan_jenkins_job_plan_script_bind_time_and_more'),
        ('project', '0002_environment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='jenkins_job',
            field=models.ForeignKey(blank=True, help_text='选择要定时执行的Jenkins Job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronjobs', to='jenkins_integration.jenkinsjob', verbose_name='Jenkins任务'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.environment', verbose_name='测试环境'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan', verbose_name='测试计划'),
        ),
    ]
