# Generated by Django 5.2.9 on 2025-12-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_cronjob_jenkins_job_alter_cronjob_env_and_more'),
        ('jenkins_integration', '0006_remove_jenkinsjob_idx_jenkins_job_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='task_type',
            field=models.CharField(default='plan', help_text='plan: 执行测试计划, jenkins_job: 构建Jenkins Job', max_length=20, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='jenkins_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cronjobs', to='jenkins_integration.jenkinsjob', verbose_name='Jenkins Job'),
        ),
    ]
