# Generated by Django 5.2.9 on 2025-12-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0003_cronjob_task_type_alter_cronjob_jenkins_job'),
        ('plan', '0003_remove_plan_jenkins_job_plan_script_bind_time_and_more'),
        ('project', '0002_environment_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='jenkins_job',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.environment', verbose_name='测试环境'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan', verbose_name='测试计划'),
        ),
    ]
