# Generated by Django 5.2.9 on 2025-12-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='节点描述')),
                ('num_executors', models.IntegerField(default=1, verbose_name='执行器数量')),
                ('labels', models.CharField(blank=True, max_length=200, verbose_name='节点标签')),
                ('is_online', models.BooleanField(default=True, verbose_name='是否在线')),
                ('is_idle', models.BooleanField(default=True, verbose_name='是否空闲')),
                ('offline_cause', models.TextField(blank=True, null=True, verbose_name='离线原因')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Jenkins 节点',
                'verbose_name_plural': 'Jenkins 节点',
                'db_table': 'jenkins_node',
            },
        ),
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Job 名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job 描述')),
                ('config_xml', models.TextField(blank=True, null=True, verbose_name='Job 配置 XML')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='构建参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_buildable', models.BooleanField(default=True, verbose_name='是否可构建')),
                ('job_type', models.CharField(default='freestyle', help_text='freestyle/pipeline/maven', max_length=20, verbose_name='Job 类型')),
                ('last_build_number', models.IntegerField(blank=True, null=True, verbose_name='最后构建编号')),
                ('last_build_status', models.CharField(blank=True, max_length=20, verbose_name='最后构建状态')),
                ('last_build_time', models.DateTimeField(blank=True, null=True, verbose_name='最后构建时间')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_by', models.CharField(max_length=20, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_jobs', to='project.environment', verbose_name='测试环境')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_jobs', to='plan.plan', verbose_name='关联测试计划')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_jobs', to='project.project', verbose_name='关联项目')),
                ('nodes', models.ManyToManyField(blank=True, help_text='选择任务执行的节点（可多选，留空则使用默认节点）', related_name='jobs', to='jenkins_integration.jenkinsnode', verbose_name='执行节点列表')),
            ],
            options={
                'verbose_name': 'Jenkins 任务',
                'verbose_name_plural': 'Jenkins 任务',
                'db_table': 'jenkins_job',
            },
        ),
        migrations.CreateModel(
            name='AllureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.IntegerField(verbose_name='构建编号')),
                ('total', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed', models.IntegerField(default=0, verbose_name='通过数量')),
                ('failed', models.IntegerField(default=0, verbose_name='失败数量')),
                ('broken', models.IntegerField(default=0, verbose_name='损坏数量')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过数量')),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='通过率（%）')),
                ('duration', models.IntegerField(default=0, verbose_name='总耗时（毫秒）')),
                ('start_timestamp', models.BigIntegerField(verbose_name='测试开始时间戳')),
                ('stop_timestamp', models.BigIntegerField(verbose_name='测试结束时间戳')),
                ('allure_url', models.URLField(verbose_name='Allure 报告 URL')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jenkins_integration.jenkinsjob', verbose_name='所属 Job')),
            ],
            options={
                'verbose_name': 'Allure 报告',
                'verbose_name_plural': 'Allure 报告',
                'db_table': 'allure_report',
            },
        ),
        migrations.CreateModel(
            name='JenkinsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='服务器名称')),
                ('url', models.URLField(verbose_name='Jenkins URL')),
                ('username', models.CharField(max_length=50, verbose_name='认证用户名')),
                ('token', models.CharField(max_length=255, verbose_name='API Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='服务器描述')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最后连接测试时间')),
                ('connection_status', models.CharField(default='unknown', help_text='connected/failed/unknown', max_length=20, verbose_name='连接状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(max_length=20, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Jenkins 服务器',
                'verbose_name_plural': 'Jenkins 服务器',
                'db_table': 'jenkins_server',
                'indexes': [models.Index(fields=['is_active'], name='idx_jenkins_server_active')],
            },
        ),
        migrations.AddField(
            model_name='jenkinsnode',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='jenkins_integration.jenkinsserver', verbose_name='所属 Jenkins 服务器'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jenkins_integration.jenkinsserver', verbose_name='所属 Jenkins 服务器'),
        ),
        migrations.CreateModel(
            name='AllureTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Allure 内部生成的唯一标识，用于日志下载', max_length=64, unique=True, verbose_name='用例唯一标识')),
                ('history_id', models.CharField(help_text='用于识别同一个用例在不同构建中的表现', max_length=64, verbose_name='用例历史 ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('full_name', models.CharField(blank=True, max_length=500, verbose_name='用例完整路径')),
                ('status', models.CharField(help_text='passed/failed/broken/skipped', max_length=20, verbose_name='用例状态')),
                ('duration', models.IntegerField(default=0, verbose_name='执行时长（毫秒）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用例描述')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('error_trace', models.TextField(blank=True, null=True, verbose_name='错误堆栈')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='测试步骤')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='日志、截图等附件列表', verbose_name='附件信息')),
                ('labels', models.JSONField(blank=True, default=dict, verbose_name='标签信息')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='参数信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='jenkins_integration.allurereport', verbose_name='所属报告')),
            ],
            options={
                'verbose_name': 'Allure 测试用例',
                'verbose_name_plural': 'Allure 测试用例',
                'db_table': 'allure_test_case',
                'indexes': [models.Index(fields=['report'], name='idx_allure_testcase_report'), models.Index(fields=['uid'], name='idx_allure_testcase_uid'), models.Index(fields=['history_id'], name='idx_allure_testcase_history'), models.Index(fields=['status'], name='idx_allure_testcase_status')],
            },
        ),
        migrations.AddIndex(
            model_name='allurereport',
            index=models.Index(fields=['job'], name='idx_allure_report_job'),
        ),
        migrations.AddIndex(
            model_name='allurereport',
            index=models.Index(fields=['create_time'], name='idx_allure_report_create'),
        ),
        migrations.AddIndex(
            model_name='allurereport',
            index=models.Index(fields=['start_timestamp'], name='idx_allure_report_start'),
        ),
        migrations.AlterUniqueTogether(
            name='allurereport',
            unique_together={('job', 'build_number')},
        ),
        migrations.AddIndex(
            model_name='jenkinsnode',
            index=models.Index(fields=['server'], name='idx_jenkins_node_server'),
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsnode',
            unique_together={('server', 'name')},
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['server'], name='idx_jenkins_job_server'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['project'], name='idx_jenkins_job_project'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['plan'], name='idx_jenkins_job_plan'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['environment'], name='idx_jenkins_job_env'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['is_active'], name='idx_jenkins_job_active'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['last_build_time'], name='idx_jenkins_job_build_time'),
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsjob',
            unique_together={('server', 'name')},
        ),
    ]
