# Generated by Django 5.2.9 on 2025-12-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsnode',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址'),
        ),
    ]
