# Generated by Django 5.2.9 on 2025-12-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0002_jenkinsnode_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsnode',
            name='is_ip_manual',
            field=models.BooleanField(default=False, help_text='标记IP地址是否为手动设置，True时同步不会覆盖', verbose_name='IP是否手动设置'),
        ),
    ]
