# Generated by Django 5.2.9 on 2025-12-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0003_add_is_ip_manual_to_node'),
        ('project', '0002_environment_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jenkinsjob',
            name='idx_jenkins_job_env',
        ),
        migrations.RemoveField(
            model_name='jenkinsjob',
            name='environment',
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='environments',
            field=models.ManyToManyField(blank=True, help_text='可选择多个测试环境', related_name='jenkins_jobs', to='project.environment', verbose_name='测试环境列表'),
        ),
    ]
