# Generated by Django 5.2.9 on 2025-12-24 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0004_remove_jenkinsjob_idx_jenkins_job_env_and_more'),
        ('plan', '0001_initial'),
        ('project', '0002_environment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='is_multi_node_parent',
            field=models.BooleanField(default=False, help_text='标记该Job是否为多节点并行的父Job', verbose_name='是否为多节点主Job'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='parent_job',
            field=models.ForeignKey(blank=True, help_text='多节点并行时，子Job指向主Job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_jobs', to='jenkins_integration.jenkinsjob', verbose_name='父任务'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='target_node',
            field=models.ForeignKey(blank=True, help_text='该Job实际运行的节点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_jobs', to='jenkins_integration.jenkinsnode', verbose_name='目标执行节点'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['parent_job'], name='idx_jenkins_job_parent'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['target_node'], name='idx_jenkins_job_target_node'),
        ),
    ]
