# Generated by Django 5.2.9 on 2025-12-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0005_jenkinsjob_is_multi_node_parent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jenkinsjob',
            name='idx_jenkins_job_parent',
        ),
        migrations.RemoveIndex(
            model_name='jenkinsjob',
            name='idx_jenkins_job_target_node',
        ),
    ]
