# Generated by Django 5.2.9 on 2025-12-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0006_remove_jenkinsjob_idx_jenkins_job_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='cron_enabled',
            field=models.BooleanField(default=False, help_text='是否启用定时执行', verbose_name='启用定时任务'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='cron_schedule',
            field=models.CharField(blank=True, help_text='Jenkins cron语法，如: H 18 * * *', max_length=100, null=True, verbose_name='Cron表达式'),
        ),
    ]
