# Generated by Django 5.2.9 on 2025-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_integration', '0007_jenkinsjob_cron_enabled_jenkinsjob_cron_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='pipeline_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pipeline 可视化配置'),
        ),
    ]
